GerenciarJogos.MVC/Controllers/AmigoController.cs
using AutoMapper;
using GerenciarJogos.Application.Interface;
using GerenciarJogos.Domain.Entities;
using GerenciarJogos.MVC.Models;
using System.Web.Mvc;

namespace GerenciarJogos.MVC.Controllers
{
    public class AmigoController : Controller
    {
        #region [CONSTANTES]
        public IAmigoAppService _amigoService;
        #endregion

        #region [CONSTRUTOR]
        public AmigoController(IAmigoAppService amigoService)
        {
            _amigoService = amigoService;
        }
        #endregion

        #region [ACOES]
        public ActionResult Index()
        {
            AmigoViewModel model = new AmigoViewModel();
            return View(model);
        }

        public ActionResult Visualizar(int codigo)
        {
            AmigoViewModel modelVM = new AmigoViewModel();

            var model = _amigoService.RecuperarPorId(codigo);
            if (model != null)
                modelVM = Mapper.Map<Amigo, AmigoViewModel>(model);

            return View(modelVM);
        }
        #endregion

    }
}

GerenciarJogos.MVC/Controllers/JogoController.cs
using AutoMapper;
using GerenciarJogos.Application.Interface;
using GerenciarJogos.Domain.Entities;
using GerenciarJogos.MVC.Models;
using System.Linq;
using System.Web.Mvc;

namespace GerenciarJogos.MVC.Controllers
{
    public class JogoController : Controller
    {
        #region [CONSTANTES]
        private readonly IJogoAppService _jogoService;
        private readonly ITipoConsoleAppService _consoleService;
        #endregion

        #region [CONSTRUTOR]
        public JogoController(IJogoAppService jogoService, ITipoConsoleAppService consoleService)
        {
            _jogoService = jogoService;
            _consoleService = consoleService;
        }
        #endregion

        #region [ACOES]
        public ActionResult Index()
        {
            JogoViewModel model = new JogoViewModel();
            model.Consoles = _consoleService.BuscarTodos().Where(c => c.Ativo);

            return View(model);
        }

        public ActionResult Visualizar(int codigo)
        {
            JogoViewModel modelVM = new JogoViewModel();

            var model = _jogoService.RecuperarPorId(codigo);
            if (model != null)
                modelVM = Mapper.Map<Jogo, JogoViewModel>(model);

            return View(modelVM);
        }



        #endregion

    }
}

GerenciarJogos.MVC/Controllers/TipoConsoleController.cs
using AutoMapper;
using GerenciarJogos.Application.Interface;
using GerenciarJogos.Domain.Entities;
using GerenciarJogos.MVC.Models;
using System.Web.Mvc;

namespace GerenciarJogos.Controllers
{
    public class TipoConsoleController : Controller
    {
        #region [CONSTANTES]
        public ITipoConsoleAppService _consoleService;
        #endregion

        #region [CONSTRUTOR]
        public TipoConsoleController(ITipoConsoleAppService consoleService)
        {
            _consoleService = consoleService;
        }
        #endregion

        #region [ACOES]
        public ActionResult Index()
        {
            TipoConsoleViewModel model = new TipoConsoleViewModel();
            return View(model);
        }

        public ActionResult Visualizar(int codigo)
        {
            TipoConsoleViewModel modelVM = new TipoConsoleViewModel();

            var model = _consoleService.RecuperarPorId(codigo);
            if (model != null)
                modelVM = Mapper.Map<TipoConsole, TipoConsoleViewModel>(model);

            return View(modelVM);
        }

        #endregion

    }
}

GerenciarJogos.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gerenciador de Jogos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/dataTables")
    @Scripts.Render("~/bundles/bootbox")

</head>
<body>
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Gerenciar Jogos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Console", "Index", "TipoConsole")</li>
                        <li>@Html.ActionLink("Jogos", "Index", "Jogo")</li>
                        <li>@Html.ActionLink("Amigos", "Index", "Amigo")</li>
                        <li>@Html.ActionLink("Emprestimo", "Index", "Emprestimo")</li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span>&nbsp;Bem vindo @HttpContext.Current.User.Identity.Name.ToString()</a></li>
                        <li><a href="/Login/LogOff"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Sair</a></li>
                    </ul>

                </div>
            </div>
        </div>
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="margin-top:20px;">
            <p>&copy; @DateTime.Now.Year - Alex dos Santos</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>